
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 13 21:01:17 COT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 24;
  public static final int Llave_c = 33;
  public static final int Op_booleano = 28;
  public static final int Null = 29;
  public static final int Llave_a = 32;
  public static final int If = 10;
  public static final int Void = 38;
  public static final int T_dato = 7;
  public static final int Comillas_simple = 4;
  public static final int XOR = 8;
  public static final int Else = 12;
  public static final int Break = 43;
  public static final int Corchete_c = 35;
  public static final int NOT = 9;
  public static final int Corchete_a = 34;
  public static final int Defecto = 44;
  public static final int Return = 37;
  public static final int While = 14;
  public static final int Division = 21;
  public static final int Parentesis_c = 31;
  public static final int Modulo = 22;
  public static final int Casetr = 11;
  public static final int Parentesis_a = 30;
  public static final int For = 16;
  public static final int P_coma = 39;
  public static final int EOF = 0;
  public static final int Printf = 15;
  public static final int error = 1;
  public static final int Switch = 41;
  public static final int Texto = 46;
  public static final int Caso = 42;
  public static final int Linea = 2;
  public static final int Op_atribucion = 26;
  public static final int ERROR = 48;
  public static final int Do = 13;
  public static final int Op_logico = 23;
  public static final int Dos_puntos = 40;
  public static final int Comas = 5;
  public static final int Identificador = 45;
  public static final int Texto2 = 6;
  public static final int Resta = 19;
  public static final int Especificadores = 25;
  public static final int Multiplicacion = 20;
  public static final int Op_incremento = 27;
  public static final int Numero = 47;
  public static final int Suma = 18;
  public static final int Main = 36;
  public static final int Igual = 17;
  public static final int Comillas = 3;
}

